x-veld:
  code:

services:
  veld_infer:
    build: .
    command: bash /veld/code/run.sh
    ports:
      - 8888:8888
    working_dir: /veld/code/
    volumes:
      - ./src/:/veld/code/
      - ./data/cache/:/veld/storage/cache/
    environment:
      spacy_model: null
      run_interactively: true

