x-veld:
  code:

services:
  veld_infer:
    #build: .
    image: steffrhes/veld_code_bert_embeddings:2025-09-12
    command: bash /veld/code/run.sh
    ports:
      - 8888:8888
    working_dir: /veld/code/
    volumes:
      - ./src/:/veld/code/
      - ./data/cache/:/veld/storage/cache/
    environment:
      spacy_model: null
      run_interactively: true
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

