x-veld:
  code:

services:
  veld_infer:
    build: .
    command: jupyter notebook --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    working_dir: /veld/code/
    volumes:
      - ./src/:/veld/code/
      - ./data/cache/:/veld/storage/cache/

